require_relative '../../node_modules/.pnpm/@capacitor+ios@5.6.0_@capacitor+core@5.6.0/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/.pnpm/@capacitor+ios@5.6.0_@capacitor+core@5.6.0/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/.pnpm/@capacitor+ios@5.6.0_@capacitor+core@5.6.0/node_modules/@capacitor/ios'
  pod 'CapacitorCommunityFileOpener', :path => '../../node_modules/.pnpm/@capacitor-community+file-opener@1.0.6_@capacitor+core@5.6.0/node_modules/@capacitor-community/file-opener'
  pod 'CapacitorApp', :path => '../../node_modules/.pnpm/@capacitor+app@5.0.6_@capacitor+core@5.6.0/node_modules/@capacitor/app'
  pod 'CapacitorClipboard', :path => '../../node_modules/.pnpm/@capacitor+clipboard@5.0.6_@capacitor+core@5.6.0/node_modules/@capacitor/clipboard'
  pod 'CapacitorDevice', :path => '../../node_modules/.pnpm/@capacitor+device@5.0.6_@capacitor+core@5.6.0/node_modules/@capacitor/device'
  pod 'CapacitorFilesystem', :path => '../../node_modules/.pnpm/@himeka+capacitor-filesystem@file+packages+capacitor-filesystem_@capacitor+core@5.6.0/node_modules/@himeka/capacitor-filesystem'
  pod 'CapacitorShare', :path => '../../node_modules/.pnpm/@capacitor+share@5.0.6_@capacitor+core@5.6.0/node_modules/@capacitor/share'
  pod 'CapacitorStatusBar', :path => '../../node_modules/.pnpm/@capacitor+status-bar@5.0.6_@capacitor+core@5.6.0/node_modules/@capacitor/status-bar'
  pod 'CapgoCapacitorNavigationBar', :path => '../../node_modules/.pnpm/@capgo+capacitor-navigation-bar@6.0.12_@capacitor+core@5.6.0/node_modules/@capgo/capacitor-navigation-bar'
  pod 'CapacitorBlobWriter', :path => '../../node_modules/.pnpm/capacitor-blob-writer@1.1.14_@capacitor+core@5.6.0_@himeka+capacitor-filesystem@file+packages_isrl6rjorgahlm5keuqtliz2hi/node_modules/capacitor-blob-writer'
  pod 'CapacitorNativeSettings', :path => '../../node_modules/.pnpm/capacitor-native-settings@5.0.1_@capacitor+core@5.6.0/node_modules/capacitor-native-settings'
  pod 'CapacitorPluginFiledownload', :path => '../../node_modules/.pnpm/@himeka+capacitor-plugin-filedownload@file+packages+capacitor-plugin-filedownload_@capacitor+core@5.6.0/node_modules/@himeka/capacitor-plugin-filedownload'
  pod 'CapacitorPluginSafeArea', :path => '../../node_modules/.pnpm/capacitor-plugin-safe-area@2.0.6_@capacitor+core@5.6.0/node_modules/capacitor-plugin-safe-area'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
